# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252c607869b72205863e268f61a3bc3a5edadec9f34b625c8450b11257d98bcd9b61f2ab3559782c0b6ed636f2c588def9c26cf7123270926872048d60274a6b

test:
  secret_key_base: 3be308e0bc6e00e77b09318ce294bda30c2004462da0deaf613cdf88d880c9e478e253896d78a64a0e6f487c4f568e32c25a9358097a532f28b011b845341f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
